# Generated by Django 5.0.4 on 2025-06-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('slogan', models.CharField(max_length=300, verbose_name='Eslogan')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Información de la Empresa',
                'verbose_name_plural': 'Información de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Archivo de video')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/', verbose_name='Miniatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video del Inicio',
                'verbose_name_plural': 'Videos del Inicio',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MattressTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('benefits', models.TextField(verbose_name='Beneficios')),
            ],
            options={
                'verbose_name': 'Tecnología de Colchón',
                'verbose_name_plural': 'Tecnologías de Colchones',
            },
        ),
        migrations.CreateModel(
            name='Mattress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('size', models.CharField(choices=[('individual', 'Individual (90x190)'), ('semidoble', 'Semidoble (120x190)'), ('doble', 'Doble (140x190)'), ('queen', 'Queen (150x190)'), ('king', 'King (180x190)'), ('super_king', 'Super King (200x200)')], max_length=20, verbose_name='Tamaño')),
                ('firmness', models.CharField(choices=[('suave', 'Suave'), ('medio', 'Medio'), ('firme', 'Firme'), ('extra_firme', 'Extra Firme')], max_length=20, verbose_name='Firmeza')),
                ('thickness', models.PositiveIntegerField(verbose_name='Grosor (cm)')),
                ('warranty_years', models.PositiveIntegerField(verbose_name='Años de garantía')),
                ('main_image', models.ImageField(upload_to='mattresses/', verbose_name='Imagen principal')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Categoría')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mattresstechnology', verbose_name='Tecnología')),
            ],
            options={
                'verbose_name': 'Colchón',
                'verbose_name_plural': 'Colchones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MattressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mattresses/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.mattress')),
            ],
            options={
                'verbose_name': 'Imagen de Colchón',
                'verbose_name_plural': 'Imágenes de Colchones',
                'ordering': ['order'],
            },
        ),
    ]
