[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.create_superuser('jhon_matinez', 'tapisuave@liderflex.com.co', 'estefania1')\" || echo 'User already exists' && python manage.py migrate_to_cloudinary && python manage.py collectstatic --noinput && gunicorn colchones_project.wsgi:application"[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'MiPassword123!')\" || echo 'User already exists' && python manage.py migrate_to_cloudinary && python manage.py collectstatic --noinput && gunicorn colchones_project.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "colchones_project.settings"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
SECRET_KEY = "django-insecure-railway-2024-tapisuave-production-key"
PORT = "8000"