[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn colchones_project.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "colchones_project.settings"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
SECRET_KEY = "tu-clave-secreta-super-segura-para-produccion"
PORT = "8000"