[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py createsuperuser --noinput --username admin --email admin@example.com && python manage.py migrate_to_cloudinary && python manage.py collectstatic --noinput && gunicorn colchones_project.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "colchones_project.settings"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
SECRET_KEY = "django-insecure-railway-2024-tapisuave-production-key"
PORT = "8000"


## 游뚿 Problema: El Superusuario No Se Cre칩 Correctamente

### 游꿢 **An치lisis del Error**

La imagen muestra que el admin de Django est치 pidiendo credenciales, pero el mensaje indica que **el superusuario no existe** o **las credenciales son incorrectas**.

### 游댢 **Soluci칩n: Crear el Superusuario Correctamente**

#### **Opci칩n 1: Modificar railway.toml (Recomendado)**

Veo que tienes el <mcfile name="railway.toml" path="c:\Users\USER\Desktop\tapi_suave\railway.toml"></mcfile> abierto. Vamos a modificarlo para crear el superusuario autom치ticamente:
```toml
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py createsuperuser --noinput --username admin --email admin@example.com && python manage.py migrate_to_cloudinary && python manage.py collectstatic --noinput && gunicorn colchones_project.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "colchones_project.settings"
PYTHONUNBUFFERED = "1"
DEBUG = "False"
SECRET_KEY = "django-insecure-railway-2024-tapisuave-production-key"
PORT = "8000"